### ISSUE TITLE
Python3?

### ISSUE THREAD

**Issue by faz** [ziirish/OctoPrint-TuyaSmartplug#10]
Hi,

I just installed this for Octoprint 1.4.0 in a python3 environment. Installed fine, however, the menu is missing. See below. Thanks!

![image](https://user-images.githubusercontent.com/1255890/80991885-c2ca0e00-8e49-11ea-9df6-f35a790b6666.png)

**Comment by ziirish** [comment]
Interesting, I'll have a look when I have a chance.

**Comment by 0xAalaoui** [comment]
Simply add  `__plugin_pythoncompat__ = ">=2.7,<4"` to `__init__.py`

Source: [https://docs.octoprint.org/en/master/plugins/python3_migration.html#telling-octoprint-your-plugin-is-python-3-ready](https://docs.octoprint.org/en/master/plugins/python3_migration.html#telling-octoprint-your-plugin-is-python-3-ready)

**Comment by faz** [comment]
> Simply add `__plugin_pythoncompat__ = ">=2.7,<4"` to `__init__.py`
> 
> Source: https://docs.octoprint.org/en/master/plugins/python3_migration.html#telling-octoprint-your-plugin-is-python-3-ready

Thanks I'll give this a shot!
