### ISSUE TITLE
bug - octopi plugin manager install failure

### ISSUE THREAD

**Issue by dixieflatline76** [ziirish/OctoPrint-TuyaSmartplug#20]
Received following error when installing via octopi plugin manager

Collecting pytuya==7.0.6
Downloading https://files.pythonhosted.org/packages/35/82/a10d977c4a0879c37275e2793d983a8b7ac0f6738e937cdc159d4f3a15c1/pytuya-7.0.6.zip
ERROR: Command errored out with exit status 1:
command: /home/pi/oprint/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-OcLqoA/pytuya/setup.py'"'"'; __file__='"'"'/tmp/pip-install-OcLqoA/pytuya/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-OcLqoA/pytuya/pip-egg-info
cwd: /tmp/pip-install-OcLqoA/pytuya/
Complete output (7 lines):
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-install-OcLqoA/pytuya/setup.py", line 9, in <module>
from pytuya.const import __author__, __version__
File "pytuya/__init__.py", line 28, in <module>
import pyaes  # https://github.com/ricmoo/pyaes
ImportError: No module named pyaes
----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Error!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output

**Comment by Uniseco** [comment]
Hello,
I have the same error. I suppose that is for the python3, but I don't have any idea how program or resolve it.

**Comment by dixieflatline76** [comment]
Damn, I am not a Python guy either, but will take a look at that migration guide and see if i can make it work.

**Comment by BlaydeRunner08** [comment]
Depending on your OS and install, you'll need to run a version of these commands: 

`source ~/oprint/bin/activate
pip install pyaes==1.6.1`
