### ISSUE TITLE
unable to change icon

### ISSUE THREAD

**Issue by ShaneF1** [ziirish/OctoPrint-TuyaSmartplug#21]
Attempts to change the icon to anything from font awesome results in a blank icon. It appears that only icon-bolt is supported.

Can you give examples of other icons that work.

**Comment by ShaneF1** [comment]
Never mind -  I saw a closed ticket. Perhaps you might update the icon link to the older Font Awesone pages?

**Comment by Deses** [comment]
I'm using `fas fa-plug` and it works fine.
